name: power3d
description: "A powerful, industry-level 3D model viewer for Flutter using Babylon.js. Supports advanced controls, lighting, and object selection."
homepage: https://github.com/rashbip/power_3d
repository: https://github.com/rashbip/power_3d
issue_tracker: https://github.com/rashbip/power_3d/issues
topics:
  - three-d
  - babylonjs
  - model-viewer
  - flutter
  - graphics
version: 1.0.0
environment:
  sdk: ^3.10.8
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  path: ^1.9.0
  path_provider: ^2.1.5
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/index.html
    - assets/babylon/babylon.js
    - assets/babylon/babylonjs.loaders.min.js
    - assets/js/messaging.js
    - assets/js/camera.js
    - assets/js/lighting.js
    - assets/js/materials.js
    - assets/js/selection/core.js
    - assets/js/selection/hierarchy.js
    - assets/js/selection/visibility.js
    - assets/js/selection/bounding-box.js
    - assets/js/selection/materials.js
    - assets/js/selection/utils.js
    - assets/js/selection/styling.js
    - assets/js/selection/handling.js
    - assets/js/model-loader.js
    - assets/js/scene.js